Iter15
JinFuuMugen/go-metrics-tpl pull request #19
Opened 2023-06-28 04:23 UTC by JinFuuMugen

2023-07-01 06:43 UTC, arttet requested changes

2023-07-01 06:43 UTC, arttet commented on cmd/agent/main.go
>  	for {
How will it stop?

2023-07-01 06:43 UTC, arttet commented on internal/monitors/gopsutil_monitor.go
> +func NewGopsutilMonitor(s storage.Storage, p sender.Sender) *monitor {
Please add an interface.

2023-07-11 00:16 UTC, JinFuuMugen commented on internal/monitors/gopsutil_monitor.go
> +func NewGopsutilMonitor(s storage.Storage, p sender.Sender) *monitor {
Added interface

2023-07-11 15:47 UTC, arttet approved these changes

2023-07-16 17:41 UTC, merged